### ISSUE TITLE
Patch release of requests breaks sniffer on second load

### ISSUE THREAD

**Issue by adamgilman** [jeffh/sniffer#23]
Latest patch release of requests (v2.5.3) breaks the auto reload of sniffer. Nose tests run fine the first time but, on reload it fails. 

```
Did not find 'scent.py', running nose:
.E
======================================================================
ERROR: Failure: AttributeError ('NoneType' object has no attribute 'modules')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/adamgilman/Desktop/working/project-name/lib/python2.7/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/adamgilman/Desktop/working/project-name/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/adamgilman/Desktop/working/project-name/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/adamgilman/Desktop/working/project-name/tests/test_MockLHRAMS.py", line 6, in <module>
    from betamax import Betamax
  File "/Users/adamgilman/Desktop/working/project-name/lib/python2.7/site-packages/betamax/__init__.py", line 13, in <module>
    from .recorder import Betamax
  File "/Users/adamgilman/Desktop/working/project-name/lib/python2.7/site-packages/betamax/recorder.py", line 2, in <module>
    from . import matchers, serializers
  File "/Users/adamgilman/Desktop/working/project-name/lib/python2.7/site-packages/betamax/matchers/__init__.py", line 4, in <module>
    from .body import BodyMatcher
  File "/Users/adamgilman/Desktop/working/project-name/lib/python2.7/site-packages/betamax/matchers/body.py", line 3, in <module>
    from ..cassette.util import deserialize_prepared_request
  File "/Users/adamgilman/Desktop/working/project-name/lib/python2.7/site-packages/betamax/cassette/__init__.py", line 1, in <module>
    from .cassette import Cassette
  File "/Users/adamgilman/Desktop/working/project-name/lib/python2.7/site-packages/betamax/cassette/cassette.py", line 2, in <module>
    from .interaction import Interaction
  File "/Users/adamgilman/Desktop/working/project-name/lib/python2.7/site-packages/betamax/cassette/interaction.py", line 1, in <module>
    from .util import (deserialize_response, deserialize_prepared_request,
  File "/Users/adamgilman/Desktop/working/project-name/lib/python2.7/site-packages/betamax/cassette/util.py", line 3, in <module>
    from requests.models import PreparedRequest, Response
  File "/Users/adamgilman/Desktop/working/project-name/lib/python2.7/site-packages/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/Users/adamgilman/Desktop/working/project-name/lib/python2.7/site-packages/requests/packages/__init__.py", line 49, in load_module
    if name in sys.modules:
AttributeError: 'NoneType' object has no attribute 'modules'

----------------------------------------------------------------------
Ran 2 tests in 0.012s

FAILED (errors=1)
Failed - Back to work!
```

**Comment by adamgilman** [comment]
Sorry; this was meant to go in a different project
