### ISSUE TITLE
Got TypeError after saving watched file: unorderable types: NoneType() > int()

### ISSUE THREAD

**Issue by sebix** [jeffh/sniffer#30]
I used sniffer as usual and it worked as expected, when I got this Exception from sniffer:

    FAILED (errors=1, failures=1)
    Failed - Back to work!
    [2015-08-10 14:56:44,183 pyinotify ERROR] add_watch: cannot watch /home/sebastian/dev/intelmq/build/bdist.linux-x86_64/egg/intelmq/tests/bots/parsers WD=-1, Errno=No such file or directory (ENOENT)
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/sniffer/main.py", line 87, in main
        test_args, options.debug)
      File "/usr/local/lib/python3.4/dist-packages/sniffer/main.py", line 48, in run
        scanner.loop(wait_time)
      File "/usr/local/lib/python3.4/dist-packages/sniffer/scanner/pyinotify_scanner.py", line 69, in loop
        self._notifier.loop(callback)
      File "/usr/lib/python3/dist-packages/pyinotify.py", line 1395, in loop
        self.process_events()
      File "/usr/lib/python3/dist-packages/pyinotify.py", line 1292, in process_events
        self._default_proc_fun(revent)
      File "/usr/lib/python3/dist-packages/pyinotify.py", line 932, in __call__
        return _ProcessEvent.__call__(self, event)
      File "/usr/lib/python3/dist-packages/pyinotify.py", line 657, in __call__
        return meth(event)
      File "/usr/local/lib/python3.4/dist-packages/sniffer/scanner/pyinotify_scanner.py", line 27, in process_IN_MODIFY
        self._scanner.trigger_modified(event.pathname)
      File "/usr/local/lib/python3.4/dist-packages/sniffer/scanner/base.py", line 42, in trigger_modified
        if mod_time > self._watched_files.get(filepath, 0):
    TypeError: unorderable types: NoneType() > int()

I am using 0.3.5 from pip on Linux (inotify):

    $ sniffer --version
    sniffer 0.3.5
    $ pip freeze | grep sniffer
    sniffer==0.3.5

**Comment by jeffh** [comment]
Hey @sebix, what are you doing to cause this bug to occur? I don't run linux these days, so I can't verify a fix ATM.

**Comment by sebix** [comment]
I got the error several times, but now I can't reproduce it for one month.

All I found out, that sniffer kind of "hangs" often in my case, it does not execute the tests anymore, just waits. Maybe has something to do with large tests and frequent changes. As I can't say more, I will close the issue here.

**Comment by jacebrowning** [comment]
I can reproduce this fairly regularly with the same version.

My `@runnable` deletes and creates files in the watched directory. It seems like there is a race condition between checking for the existence of a file and checking its modification time.
